//
export const LOAD_PRODUCTS_INIT = 'LOAD_PRODUCTS_INIT';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';

export const LOAD_MORE_PRODUCTS_INIT = 'LOAD_MORE_PRODUCTS_INIT';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_ERROR = 'LOAD_MORE_PRODUCTS_ERROR';

export const SET_FILTER_BY = 'SET_FILTER_BY';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_PAGE_TO_LOAD = 'SET_PAGE_TO_LOAD';

export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_PRODUCTS_FROM_CART = 'REMOVE_PRODUCTS_FROM_CART';

export const LOAD_PRODUCT_INIT = 'LOAD_PRODUCT_INIT';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_ERROR = 'LOAD_PRODUCT_ERROR';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';

export const REDIRECT_AFTER_LOGIN = 'REDIRECT_AFTER_LOGIN';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
// export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const LOGIN_GET_TOKEN = 'LOGIN_GET_TOKEN';
export const LOGOUT_REMOVE_TOKEN = 'LOGOUT_REMOVE_TOKEN';

export const CALCULATE_MSDP = 'CALCULATE_MSDP';
export const SET_MDSP = 'SET_MDSP';

export const SET_CURRENT_CAR_ID = 'SET_CURRENT_CAR_ID';
export const SET_CURRENT_CAR_IMG = 'SET_CURRENT_CAR_IMG';
export const SET_CURRENT_CAR_NAME = 'SET_CURRENT_CAR_NAME';

export const LOAD_ORDERS_ERROR = 'LOAD_ORDERS_ERROR';
export const LOAD_ORDERS_INIT = 'LOAD_ORDERS_INIT';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';

export const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
export const LOAD_BOOKS_INIT = 'LOAD_BOOKS_INIT';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';